behaviors:
  TankAgent:
    trainer_type: ppo
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 5000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 2.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
